apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card-order-service
  labels:
    owner: team-payments
  annotations:
    owner: team-payments
spec:
  selector:
    matchLabels:
      app: credit-card-order-service
  template:
    metadata:
      labels:
        app: credit-card-order-service
        owner: team-payments
    spec:
      initContainers:
        - name: download-debugging-agent
          image: alpine:latest
          command:
            - /bin/sh
          args:
            - -c
            - wget -O /opt/devobs/rookout.jar "https://search.maven.org/remote_content?g=com.rookout&a=rook&v=0.1.265"
          volumeMounts:
            - mountPath: /opt/devobs
              name: debugger
      containers:
        - name: credit-card-order-service
          image: gcr.io/dynatrace-demoability/easytrade/credit-card-order-service:151f288
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: feature-flag-service-setup
          env:
            - name: PROXY_PREFIX
              value: "credit-card-order-service"
            - name: THIRD_PARTY_SERVICE_HOSTANDPORT
              value: "third-party-service:8080"
            - name: WORK_DELAY
              value: "300"
            - name: WORK_RATE
              value: "900"
            - name: ROOKOUT_TOKEN
              value: "b1789f6c0d944712904d4b81ba982d9ffdf540fa4fde42eda44698e1db906f0e"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/opt/devobs/rookout.jar"
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: JAVA_CONNECTION_STRING
          volumeMounts:
            - mountPath: /opt/devobs
              name: debugger
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 150m
              memory: 350Mi
      volumes:
        - name: debugger
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: credit-card-order-service
spec:
  type: ClusterIP
  selector:
    app: credit-card-order-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
